name: Build and Deploy to GitHub Pages

on:
  workflow_dispatch: # for manual run
  push:
    branches:
      - master

permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4
        with:
          path: $GITHUB_WORKSPACE/repo

      - name: Copy files to the build folder ğŸšš
        run: |
          cp --recursive $GITHUB_WORKSPACE/repo $GITHUB_WORKSPACE/build

      - name: Setup Pages ğŸ”§
        id: pages
        uses: actions/configure-pages@v5

      - name: Install Node.JS dependencies ğŸ”¨
        run: |
          npm install

      - name: Run the build script to snapshot all .shtml files ğŸ“¸
        run: |
          npm build <(find . -type f -name "*.shtml") $GITHUB_WORKSPACE/build

      - name: Upload artifact ğŸ“¦ï¸
        uses: actions/upload-pages-artifact@v3
        with:
          path: $GITHUB_WORKSPACE/build

  deploy:
    permissions: # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
      pages: write    # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages ğŸš€
        id: deployment
        uses: actions/deploy-pages@v4
